# Generated by Django 5.2 on 2025-04-17 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_optimizedaddress_optimizedappuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerrelationship",
            name="appuser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customerrelationship",
                to="crm.appuser",
            ),
        ),
    ]
